name: e2e-sentry-flutter
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths:
      - "!**/*.md"
      - "!**/class-diagram.svg"
      - ".github/workflows/e2e_flutter.yml"
      - "dart/**"
      - "flutter/**"
      - "e2e_test/flutter/**"

env:
  SENTRY_AUTH_TOKEN_E2E: ${{ secrets.SENTRY_AUTH_TOKEN_E2E }}
  SENTRY_DIST: 1

jobs:
  cancel-previous-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # pin@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    name: E2E Flutter
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./e2e_test/flutter
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - name: Install Maestro
        run: brew tap mobile-dev-inc/tap && brew install mobile-dev-inc/tap/maestro@1.38
      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # pin@v2.16.0
        with:
          channel: ${{ matrix.sdk }}
      - run: flutter upgrade
      - name: Pub Get
        run: flutter pub get
      - name: Run
        if: env.SENTRY_AUTH_TOKEN != null
        run: |
          flutter build ios --debug --simulator --obfuscate --split-debug-info=./
          xcrun simctl install Booted build/ios/iphonesimulator/Runner.app
          maestro test flow.yaml
          
#  analyze:
#    uses: ./.github/workflows/analyze.yml
#    with:
#      package: e2e_test/flutter
#      panaThreshold: 0
