name: Upload to Testflight
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/testflight.yml'

jobs:
  upload_to_testflight:
    name: Build and Upload to Testflight
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # pin@v2.10.0
      - run: ./scripts/ci-select-xcode.sh
      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # pin@v1.152.0
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: flutter
        working-directory: ./flutter/example/ios
        run: |
          flutter upgrade
          flutter pub get
          flutter build ios --no-codesign

      # We upload a new version to TestFlight on every commit on main
      # So we need to bump the build number each time
      - name: Bump Build Number
        working-directory: ./flutter/example/ios
        env:
          FASTLANE_BUILD_NUMBER: ${{ github.run_number }}
        run: bundle exec fastlane bump_build_number

      - name: Build & Upload with Fastlane
        working-directory: ./flutter/example/ios
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          FASTLANE_BUNDLE_VERSION: ${{ github.run_number }}
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          bundle exec fastlane build
          bundle exec fastlane testflight
